### ISSUE TITLE
Automate configuration of nodes created by terraform

### ISSUE THREAD

**Issue by Naman1997** [Naman1997/kubernetes-configs#4]
Install packages and do initial setup with either ansibe/bash scripts.
Initial setup includes :
- Installing arch with archinstall using [this](https://github.com/Naman1997/kubernetes-configs/blob/master/kubeadm/archinstall_config.json) config
- Install packages depending on kmaster/kworker
- Setup zsh according to commands present [here](https://github.com/Naman1997/Terminal-themes/blob/main/zsh/README.md)

**Comment by Naman1997** [comment]
Probably will need a bash script with a local-exec provider as shown [here](https://www.terraform.io/docs/language/resources/provisioners/local-exec.html)

**Comment by Naman1997** [comment]
Probably need to work with ssh_forward_ip and other options specified [here](https://github.com/Telmate/terraform-provider-proxmox/issues/271#issuecomment-764673778)

Also will need a "null_resource" if we want to make the initial setup optional.
Probably something like this:

```
resource "null_resource" "cluster" {
  count = var.common_configs.setup_arch ? 1 : 0

  triggers = {
    always_run = "${timestamp()}"
  }

  # Need to figure how to either connect this with all VMs
  # or make a null_resource work selectively
  connection {
    type     = "ssh"
    host     = proxmox_vm_qemu.kmaster.ssh_host
    user     = proxmox_vm_qemu.kmaster.ssh_user
    port     = proxmox_vm_qemu.kmaster.ssh_port
  }

  # Will need to login as root somehow
  provisioner "remote-exec" {
    inline = [
      "pacman -Syyy",
      "pacman -S archinstall",
      # Need to figure how to replace passwords, hostname and timezone per user requirement
      "archinstall --config https://raw.githubusercontent.com/Naman1997/kubernetes-configs/master/kubeadm/archinstall_config.json"
    ]
  }
}
```

**Comment by Naman1997** [comment]
Need to understand [cloud-init](https://registry.terraform.io/providers/Telmate/proxmox/latest/docs/guides/cloud_init) on proxmox along with [headless installation](https://wiki.archlinux.org/title/Install_Arch_Linux_via_SSH#Installation_on_a_headless_server) for arch

**Comment by Naman1997** [comment]
Not able to ssh in the live install. Need to now figure out how to run commands from cloud-init and then remove the live iso cd somehow after the commands have executed and arch is setup.

Current config is:

```
# The top level settings are used as module
# and system configuration.

# A set of users which may be applied and/or used by various modules
# when a 'default' entry is found it will reference the 'default_user'
# from the distro configuration specified below
users:
   - default

# If this is set, 'root' will not be able to ssh in and they
# will get a message to login instead as the default $user
disable_root: true

# The modules that run in the 'init' stage
cloud_init_modules:
 - migrator
 - seed_random
 - bootcmd
 - write-files
 - growpart
 - resizefs
 - disk_setup
 - mounts
 - set_hostname
 - update_hostname
 - update_etc_hosts
 - ca-certs
 - rsyslog
 - users-groups
 - ssh

# The modules that run in the 'config' stage
cloud_config_modules:
 - ssh-import-id
 - locale
 - ntp
 - timezone "Asia/Kolkata"

# The modules that run in the 'final' stage
cloud_final_modules:
 - package-update-upgrade-install

# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
   # This will affect which distro class gets used
   distro: arch
   # Default user name + that default users groups (if added/used)
   default_user:
     name: arch
     lock_passwd: True
     gecos: arch Cloud User
     groups: [wheel, users]
     sudo: ["ALL=(ALL) NOPASSWD:ALL"]
     shell: /bin/bash
     ssh_authorized_keys:
      - ssh-rsa {{KEY}}
   # Other config here will be given to the distro class and/or path classes
   paths:
      cloud_dir: /var/lib/cloud/
      templates_dir: /etc/cloud/templates/
   ssh_svcname: sshd

bootcmd:
  - yes | archinstall --config https://raw.githubusercontent.com/Naman1997/kubernetes-configs/master/kubeadm/archinstall_config.json

packages:
  - archinstall
```

This currently is not executing bootcmd or packages section. Also for some reason, the default user is not created and the ssh key goes straight to authorized_keys. Need to figure out why.
Logs for this can be found in `/var/log/cloud-init-output.log`

**Comment by Naman1997** [comment]
Removed extra configuration and was able to install arch with a config in cloud-init. We cannot setup k8s packages and zsh in this step because its now more of a post-provisioning step. Those items will be moved to a new issue.

Current config being used:
```
#cloud-config
users:
  - name: root
    ssh_authorized_keys:
      - ssh-rsa {{KEY}}
runcmd:
  - pacman -Syyy
  - pacmen -S archinstall
  - echo "===========================INSTALLING ARCH TO DRIVE================================"
  - yes | archinstall --config https://raw.githubusercontent.com/Naman1997/kubernetes-configs/master/kubeadm/archinstall_config.json
```

Need to update the config in this URL as its causing some issues while installing. Probably will need to read the code for archinstall and figure what params are missing.
